package restaxis

// This file ports gen_grid.py: it generates the rest-axis ablation grid study
// TOMLs, one per (glyph, scenario) for a single model. Each study embeds the
// model's [model] section verbatim (extracted from a source TOML) so the prompt
// template escaping is never hand-transcribed, plus the lab-standard sampler
// chain, the ablation arms, and the pinned image digest.
//
// The logic here is sans-IO: ExtractModelBlock takes the source TOML's contents
// as a string, and GenGrid returns the study TOML text per cell. All file IO and
// path resolution live in cmd/corpos-lab/restaxis_gengrid.go.

import (
	"fmt"
	"strings"
)

// GridSpec is the full sans-IO input for one grid generation. It produces one
// study TOML per (glyph, scenario) for the single model named by ModelTag.
type GridSpec struct {
	Glyphs      []string // outer loop; one study directory per glyph
	Scenarios   []int    // inner loop; one study TOML per scenario
	ModelTag    string   // model tag, e.g. "qwen38"; used in the name, header, and filename
	ModelBlock  string   // the verbatim [model] section, ending with a newline (see ExtractModelBlock)
	Image       string   // the content-digest image reference
	Conditions  []string // the matched arms, rendered as the conditions list
	RunsPerCell int      // runs per grid cell
	Seeds       []int    // sampler seeds
}

// Cell is one generated study TOML and the coordinates it was generated for.
type Cell struct {
	Glyph    string
	Scenario int
	TOML     string
}

// StudyFileName returns the study TOML filename for a (model tag, scenario),
// matching gen_grid.py's "study.{tag}.s{s}.toml". The file belongs under the
// per-glyph directory; the caller joins it with the glyph and output dir.
func StudyFileName(modelTag string, scenario int) string {
	return fmt.Sprintf("study.%s.s%d.toml", modelTag, scenario)
}

// GenGrid returns one Cell per (glyph, scenario), glyph outer and scenario
// inner, matching gen_grid.gen for a single model tag.
func GenGrid(s GridSpec) []Cell {
	out := make([]Cell, 0, len(s.Glyphs)*len(s.Scenarios))
	for _, glyph := range s.Glyphs {
		for _, scenario := range s.Scenarios {
			out = append(out, Cell{
				Glyph:    glyph,
				Scenario: scenario,
				TOML:     s.render(glyph, scenario),
			})
		}
	}
	return out
}

// render builds one study TOML. The header comment, the "grounded-glyph-probe"
// assay, the "corpos-net" network, and the sampler tail are fixed lab-standard
// text carried verbatim from gen_grid.py so the output reproduces byte-for-byte.
func (s GridSpec) render(glyph string, scenario int) string {
	name := fmt.Sprintf("rest-axis-overhead-%s-s%d-%s", glyph, scenario, s.ModelTag)
	var b strings.Builder
	// Header comment. The em-dashes and the "3 arms … x 8 seeds = 24 runs" and
	// "Generated by scratchpad/gen_grid.py" lines are copied verbatim from the
	// python so the committed study TOMLs reproduce exactly.
	fmt.Fprintf(&b, "# Rest-axis overhead benchmark — %s — scenario %d — %s.\n", glyph, scenario, s.ModelTag)
	b.WriteString("# Grid cell: 3 arms (no_glyph / glyph_full / glyph_minus_rest) x 8 seeds = 24 runs.\n")
	b.WriteString("# Generated by scratchpad/gen_grid.py. Material paths resolve relative to THIS file.\n\n")

	fmt.Fprintf(&b, "name = %s\n", tomlString(name))
	b.WriteString("assay = \"grounded-glyph-probe\"\n")
	fmt.Fprintf(&b, "item_id = %s\n\n", tomlString(glyph))

	fmt.Fprintf(&b, "image = %s\n", tomlString(s.Image))
	b.WriteString("network = \"corpos-net\"\n\n")

	fmt.Fprintf(&b, "conditions = %s\n", renderStrList(s.Conditions))
	fmt.Fprintf(&b, "runs_per_cell = %d\n\n", s.RunsPerCell)

	// ModelBlock ends with a newline; the extra "\n" reproduces the blank line
	// gen_grid.py places between the [model] block and [materials].
	b.WriteString(s.ModelBlock)
	b.WriteString("\n[materials]\n")
	fmt.Fprintf(&b, "scenario         = \"materials/scenario_%d.md\"\n", scenario)
	b.WriteString("glyph            = \"materials/glyph_full.md\"\n")
	b.WriteString("glyph_minus_rest = \"materials/glyph_minus_rest.md\"\n\n")

	b.WriteString(renderSampling(s.Seeds))
	return b.String()
}

// samplingTail is the fixed lab-standard sampler chain from max_tokens onward,
// carried verbatim from gen_grid.SAMPLING. Only the seeds vary per call.
const samplingTail = `max_tokens = 1024

top_n_sigma = -1.0
top_k = 0
typical_p = 1.0
top_p = 1.0
min_p = 0.05

repeat_penalty = 1.0
repeat_last_n = 0
presence_penalty = 0.0
frequency_penalty = 0.0

xtc_probability = 0.0
dry_multiplier = 0.0
`

// renderSampling builds the [sampling] block with the given seeds. Temperature
// and the rest of the chain are the fixed lab-standard regime (gen_grid.SAMPLING).
func renderSampling(seeds []int) string {
	var b strings.Builder
	b.WriteString("[sampling]\n")
	b.WriteString("temperature = 0.8\n")
	fmt.Fprintf(&b, "seeds = %s\n", renderIntList(seeds))
	b.WriteString(samplingTail)
	return b.String()
}

// ExtractModelBlock returns the [model] section of a study TOML verbatim, from
// the "[model]" line to the next section header, with trailing blank lines
// trimmed and a single trailing newline appended. Ported sans-IO from
// gen_grid.extract_model_block: the caller passes the source TOML's contents.
func ExtractModelBlock(src string) string {
	var out []string
	capturing := false
	for _, ln := range splitLines(src) {
		stripped := strings.TrimSpace(ln)
		if stripped == "[model]" {
			capturing = true
			out = append(out, ln)
			continue
		}
		if capturing {
			if strings.HasPrefix(stripped, "[") && strings.HasSuffix(stripped, "]") && stripped != "[model]" {
				break
			}
			out = append(out, ln)
		}
	}
	// Trim trailing blank lines, matching the python while-pop.
	for len(out) > 0 && strings.TrimSpace(out[len(out)-1]) == "" {
		out = out[:len(out)-1]
	}
	return strings.Join(out, "\n") + "\n"
}

// splitLines splits text into lines the way python's str.splitlines() does for
// the cases these TOMLs use: it splits on "\n" and does not yield a trailing
// empty element for a final newline.
func splitLines(s string) []string {
	if s == "" {
		return nil
	}
	s = strings.ReplaceAll(s, "\r\n", "\n")
	s = strings.TrimSuffix(s, "\n")
	return strings.Split(s, "\n")
}

// renderIntList renders a slice of ints as a python list literal, e.g.
// [1, 2, 3]. An empty slice renders as [].
func renderIntList(xs []int) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = fmt.Sprintf("%d", x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// renderStrList renders a slice of strings as a python list of double-quoted
// strings, e.g. ["baseline", "glyph_only"]. An empty slice renders as [].
func renderStrList(xs []string) string {
	parts := make([]string, len(xs))
	for i, x := range xs {
		parts[i] = tomlString(x)
	}
	return "[" + strings.Join(parts, ", ") + "]"
}

// tomlString renders a basic double-quoted TOML/JSON string. The values these
// studies use (names, glyphs, image digests, arm names) contain no control
// characters or quotes, so a minimal escaper of `"` and `\` suffices and matches
// the python f-string / repr output.
func tomlString(s string) string {
	r := strings.NewReplacer(`\`, `\\`, `"`, `\"`)
	return `"` + r.Replace(s) + `"`
}
