package restaxis

import (
	"strings"
	"testing"
)

// defaultSpec is a GridSpec matching gen_grid.py's constants for one model.
func defaultSpec() GridSpec {
	return GridSpec{
		Glyphs:      []string{"casg-direct"},
		Scenarios:   []int{1},
		ModelTag:    "qwen38",
		ModelBlock:  "[model]\nbase_url = \"http://llama-server:8081/v1\"\nmodel_id = \"Qwen3.8-27B-Q4_K_M.gguf\"\n",
		Image:       "localhost/lab-grounded-glyph-probe@sha256:abc",
		Conditions:  []string{"baseline", "glyph_only", "glyph_minus_rest"},
		RunsPerCell: 3,
		Seeds:       []int{1, 2, 3},
	}
}

func TestExtractModelBlock(t *testing.T) {
	cases := []struct {
		name string
		src  string
		want string
	}{
		{
			name: "basic block trims trailing blank before next section",
			src:  "name = \"x\"\n\n[model]\nbase_url = \"u\"\nmodel_id = \"m\"\n\n[materials]\nscenario = \"s\"\n",
			want: "[model]\nbase_url = \"u\"\nmodel_id = \"m\"\n",
		},
		{
			name: "block at end of file with trailing newline",
			src:  "[model]\nbase_url = \"u\"\n",
			want: "[model]\nbase_url = \"u\"\n",
		},
		{
			name: "block at end of file without trailing newline",
			src:  "[model]\nbase_url = \"u\"",
			want: "[model]\nbase_url = \"u\"\n",
		},
		{
			name: "interior blank lines are preserved",
			src:  "[model]\na = 1\n\nb = 2\n[materials]\n",
			want: "[model]\na = 1\n\nb = 2\n",
		},
		{
			name: "indented section header is trimmed then recognized",
			src:  "[model]\na = 1\n  [materials]\nb = 2\n",
			want: "[model]\na = 1\n",
		},
		{
			name: "no model section yields just a newline",
			src:  "name = \"x\"\n[materials]\nscenario = \"s\"\n",
			want: "\n",
		},
		{
			name: "empty source yields just a newline",
			src:  "",
			want: "\n",
		},
		{
			name: "crlf line endings are handled",
			src:  "[model]\r\nbase_url = \"u\"\r\n[materials]\r\n",
			want: "[model]\nbase_url = \"u\"\n",
		},
		{
			name: "content before model is skipped",
			src:  "# comment\nname = \"x\"\n[model]\nk = \"v\"\n[sampling]\n",
			want: "[model]\nk = \"v\"\n",
		},
	}
	for _, c := range cases {
		t.Run(c.name, func(t *testing.T) {
			if got := ExtractModelBlock(c.src); got != c.want {
				t.Errorf("ExtractModelBlock(%q)\n got %q\nwant %q", c.src, got, c.want)
			}
		})
	}
}

func TestStudyFileName(t *testing.T) {
	cases := []struct {
		tag  string
		s    int
		want string
	}{
		{"qwen38", 1, "study.qwen38.s1.toml"},
		{"mistral", 20, "study.mistral.s20.toml"},
		{"phi4", 7, "study.phi4.s7.toml"},
	}
	for _, c := range cases {
		if got := StudyFileName(c.tag, c.s); got != c.want {
			t.Errorf("StudyFileName(%q,%d) = %q, want %q", c.tag, c.s, got, c.want)
		}
	}
}

func TestGenGridCellCountAndOrder(t *testing.T) {
	s := defaultSpec()
	s.Glyphs = []string{"g2", "g1"}
	s.Scenarios = []int{5, 3}
	cells := GenGrid(s)
	if len(cells) != 4 {
		t.Fatalf("got %d cells, want 4", len(cells))
	}
	want := []struct {
		glyph string
		scen  int
	}{{"g2", 5}, {"g2", 3}, {"g1", 5}, {"g1", 3}}
	for i, w := range want {
		if cells[i].Glyph != w.glyph || cells[i].Scenario != w.scen {
			t.Errorf("cell[%d] = %s/s%d, want %s/s%d", i, cells[i].Glyph, cells[i].Scenario, w.glyph, w.scen)
		}
	}
}

func TestGenGridEmpty(t *testing.T) {
	s := defaultSpec()
	s.Glyphs = nil
	if cells := GenGrid(s); len(cells) != 0 {
		t.Errorf("got %d cells for no glyphs, want 0", len(cells))
	}
	s = defaultSpec()
	s.Scenarios = nil
	if cells := GenGrid(s); len(cells) != 0 {
		t.Errorf("got %d cells for no scenarios, want 0", len(cells))
	}
}

func TestRenderContainsExpectedFields(t *testing.T) {
	cells := GenGrid(defaultSpec())
	toml := cells[0].TOML
	wants := []string{
		"# Rest-axis overhead benchmark — casg-direct — scenario 1 — qwen38.\n",
		"# Grid cell: 3 arms (no_glyph / glyph_full / glyph_minus_rest) x 8 seeds = 24 runs.\n",
		"# Generated by scratchpad/gen_grid.py. Material paths resolve relative to THIS file.\n",
		"name = \"rest-axis-overhead-casg-direct-s1-qwen38\"\n",
		"assay = \"grounded-glyph-probe\"\n",
		"item_id = \"casg-direct\"\n",
		"image = \"localhost/lab-grounded-glyph-probe@sha256:abc\"\n",
		"network = \"lab-net\"\n",
		"conditions = [\"baseline\", \"glyph_only\", \"glyph_minus_rest\"]\n",
		"runs_per_cell = 3\n",
		"[model]\n",
		"[materials]\n",
		"scenario         = \"materials/scenario_1.md\"\n",
		"glyph            = \"materials/glyph_full.md\"\n",
		"glyph_minus_rest = \"materials/glyph_minus_rest.md\"\n",
		"[sampling]\n",
		"temperature = 0.8\n",
		"seeds = [1, 2, 3]\n",
		"max_tokens = 1024\n",
		"dry_multiplier = 0.0\n",
	}
	for _, w := range wants {
		if !strings.Contains(toml, w) {
			t.Errorf("TOML missing %q\n---\n%s", w, toml)
		}
	}
}

func TestRenderModelBlockBlankLineBeforeMaterials(t *testing.T) {
	toml := GenGrid(defaultSpec())[0].TOML
	// The model block ends with model_id, then a blank line, then [materials].
	if !strings.Contains(toml, "model_id = \"Qwen3.8-27B-Q4_K_M.gguf\"\n\n[materials]\n") {
		t.Errorf("expected a blank line between the model block and [materials]:\n%s", toml)
	}
}

func TestRenderEndsWithSamplingNewline(t *testing.T) {
	toml := GenGrid(defaultSpec())[0].TOML
	if !strings.HasSuffix(toml, "dry_multiplier = 0.0\n") {
		t.Errorf("TOML should end with the final sampler line + newline, got tail %q", tail(toml, 40))
	}
	// And nothing after it.
	if strings.HasSuffix(toml, "dry_multiplier = 0.0\n\n") {
		t.Errorf("TOML should not have a trailing blank line")
	}
}

func TestRenderScenarioInterpolation(t *testing.T) {
	s := defaultSpec()
	s.Scenarios = []int{14}
	toml := GenGrid(s)[0].TOML
	if !strings.Contains(toml, "scenario         = \"materials/scenario_14.md\"\n") {
		t.Errorf("scenario path not interpolated for s14:\n%s", toml)
	}
	if !strings.Contains(toml, "name = \"rest-axis-overhead-casg-direct-s14-qwen38\"\n") {
		t.Errorf("name not interpolated for s14:\n%s", toml)
	}
}

func TestRenderSeedsInterpolation(t *testing.T) {
	cases := []struct {
		seeds []int
		want  string
	}{
		{[]int{1, 2, 3}, "seeds = [1, 2, 3]\n"},
		{[]int{1}, "seeds = [1]\n"},
		{[]int{5, 6, 7, 8}, "seeds = [5, 6, 7, 8]\n"},
		{nil, "seeds = []\n"},
	}
	for _, c := range cases {
		s := defaultSpec()
		s.Seeds = c.seeds
		toml := GenGrid(s)[0].TOML
		if !strings.Contains(toml, c.want) {
			t.Errorf("seeds %v: missing %q", c.seeds, c.want)
		}
	}
}

func TestRenderConditionsAndRunsPerCell(t *testing.T) {
	s := defaultSpec()
	s.Conditions = []string{"a", "b"}
	s.RunsPerCell = 8
	toml := GenGrid(s)[0].TOML
	if !strings.Contains(toml, "conditions = [\"a\", \"b\"]\n") {
		t.Errorf("conditions not rendered:\n%s", toml)
	}
	if !strings.Contains(toml, "runs_per_cell = 8\n") {
		t.Errorf("runs_per_cell not rendered:\n%s", toml)
	}
}

func TestRenderIntList(t *testing.T) {
	cases := []struct {
		in   []int
		want string
	}{
		{[]int{1, 2, 3}, "[1, 2, 3]"},
		{[]int{42}, "[42]"},
		{nil, "[]"},
		{[]int{}, "[]"},
	}
	for _, c := range cases {
		if got := renderIntList(c.in); got != c.want {
			t.Errorf("renderIntList(%v) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestRenderStrList(t *testing.T) {
	cases := []struct {
		in   []string
		want string
	}{
		{[]string{"a", "b"}, "[\"a\", \"b\"]"},
		{[]string{"x"}, "[\"x\"]"},
		{nil, "[]"},
	}
	for _, c := range cases {
		if got := renderStrList(c.in); got != c.want {
			t.Errorf("renderStrList(%v) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestTomlStringEscaping(t *testing.T) {
	cases := []struct {
		in   string
		want string
	}{
		{"plain", "\"plain\""},
		{"has\"quote", "\"has\\\"quote\""},
		{"back\\slash", "\"back\\\\slash\""},
	}
	for _, c := range cases {
		if got := tomlString(c.in); got != c.want {
			t.Errorf("tomlString(%q) = %q, want %q", c.in, got, c.want)
		}
	}
}

func TestSplitLines(t *testing.T) {
	cases := []struct {
		in   string
		want []string
	}{
		{"", nil},
		{"a", []string{"a"}},
		{"a\n", []string{"a"}},
		{"a\nb", []string{"a", "b"}},
		{"a\nb\n", []string{"a", "b"}},
		{"a\r\nb\r\n", []string{"a", "b"}},
		{"\n", []string{""}},
	}
	for _, c := range cases {
		got := splitLines(c.in)
		if len(got) != len(c.want) {
			t.Errorf("splitLines(%q) = %v, want %v", c.in, got, c.want)
			continue
		}
		for i := range got {
			if got[i] != c.want[i] {
				t.Errorf("splitLines(%q)[%d] = %q, want %q", c.in, i, got[i], c.want[i])
			}
		}
	}
}

func tail(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[len(s)-n:]
}
