// Package behaveq ports the behavioral-equivalence-assay provenance scoring and
// generation python to Go (chain eradicate-python-rewrite-in-go). It backs the
// published paper "Duty or Corpus" (10.5281/zenodo.22716214).
//
// The four tools ported here mirror the python one-for-one:
//
//   - gen.go       — gen_expansion_defs.py: the study-def TOML generator.
//   - dp1.go       — dp1_rule_scorer.py: the deterministic DP-1 rule scorer.
//   - analyze.go   — analyze.py: the clear-rate + contrast statistics report.
//   - doublescore.go — double_score.py: the second-rater prompt/parse (pure parts).
//
// All logic is sans-IO: callers read the study's run/def files and pass the data
// in. cmd/corpos-lab/pubscore_behaveq.go does the file wiring.
package behaveq

import (
	"fmt"
	"strconv"
	"strings"
)

// expansionImage is the pinned probe image the generated study defs reference,
// ported verbatim from gen_expansion_defs.IMAGE.
const expansionImage = "localhost/lab-grounded-glyph-probe@sha256:d420b80f40889fec709f15067f5eccd8ad8219d3b616c7d53f2be45ec284f792"

// expansionNote is the single-completion disclaimer spliced into every arm's
// prompt wrapper, ported verbatim from gen_expansion_defs.NOTE.
const expansionNote = "Note: You are running as a single completion. There is no harness, no tools, " +
	"no filesystem, no shell. You cannot call functions or read files. Give your " +
	"answer directly as text."

// ExpansionArm is one model arm of the expansion study. The three arms share the
// conditions, materials, image, and sampler chain; they differ only in the model
// and its instruct wrapper. Ported from the gen_expansion_defs.ARMS entries.
type ExpansionArm struct {
	Key     string // the TOML basename ("mistral", "qwen38", "qwen2532")
	Name    string
	ModelID string
	Version string
	Wrapper string // instruct wrapper; {prompt} is the substitution point, \n are literal
	Note    string
}

// ExpansionArms are the three arms in the python dict's insertion order, which is
// the order gen_expansion_defs.main() iterates when writing the files.
var ExpansionArms = []ExpansionArm{
	{
		Key:     "mistral",
		Name:    "behavioral-equivalence-mistral",
		ModelID: "Mistral-7B-Instruct-v0.3.Q4_K_M.gguf",
		Version: "v0.3-q4km",
		Wrapper: "[INST] {prompt}\\n\\n---\\n" + expansionNote + " [/INST]",
		Note:    "Mistral-7B anchor.",
	},
	{
		Key:     "qwen38",
		Name:    "behavioral-equivalence-qwen38",
		ModelID: "Qwen3.8-27B-Q4_K_M.gguf",
		Version: "q4km",
		Wrapper: "<|im_start|>user\\n{prompt}\\n\\n---\\n" + expansionNote + "<|im_end|>\\n<|im_start|>assistant\\n<think>\\n\\n</think>\\n\\n",
		Note:    "Qwen3.8-27B, thinking pinned OFF via the closed empty <think> block.",
	},
	{
		Key:     "qwen2532",
		Name:    "behavioral-equivalence-qwen2532",
		ModelID: "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
		Version: "q4km",
		Wrapper: "<|im_start|>user\\n{prompt}\\n\\n---\\n" + expansionNote + "<|im_end|>\\n<|im_start|>assistant\\n",
		Note: "Qwen2.5-32B, non-thinking. MUST be served at ctx 8192, not 32768 " +
			"(the 32B + a 32768 KV cache overruns the 24 GB GPU; wrong-path-field-source). " +
			"Prompt ~1900 + max_tokens 4096 fits 8192.",
	},
}

// ExpansionArmByKey returns the arm with the given key, or false when none match.
func ExpansionArmByKey(key string) (ExpansionArm, bool) {
	for _, a := range ExpansionArms {
		if a.Key == key {
			return a, true
		}
	}
	return ExpansionArm{}, false
}

// seedList builds the "1, 2, ..., n" seed string, matching python
// ", ".join(str(i) for i in range(1, n+1)).
func seedList(n int) string {
	parts := make([]string, 0, n)
	for i := 1; i <= n; i++ {
		parts = append(parts, strconv.Itoa(i))
	}
	return strings.Join(parts, ", ")
}

// TOMLFor renders one arm's study-def TOML for the given n, byte-identical to
// gen_expansion_defs.toml_for(arm_key, n). The result ends with a trailing
// newline, as the python triple-quoted string does.
func TOMLFor(a ExpansionArm, n int) string {
	seeds := seedList(n)
	return fmt.Sprintf(`# Behavioral-equivalence expansion (n=%d) — %s
# Generated by gen_expansion_defs.py. Materials, conditions, image, and sampler are
# identical across the three arms; only the model and its wrapper differ.
# Run: corpos-lab run-study studies/behavioral-equivalence-assay/study-defs/n%d/%s.toml \
#        -work studies/behavioral-equivalence-assay/runs/%s-n%d

name = "%s-n%d"
assay = "grounded-glyph-probe"
item_id = "behavioral-equivalence"

image = "%s"
network = "corpos-net"

conditions = ["baseline", "duty_only", "corpus_only"]
runs_per_cell = %d

[model]
base_url = "http://llama-server:8081/v1"
model_id = "%s"
version = "%s"
endpoint = "completion"
prompt_template = "%s"

[materials]
scenario = "../../materials/scenario.md"
duty     = "../../materials/duty.md"
corpus   = "../../materials/corpus.md"

[sampling]
temperature = 0.8
seeds = [%s]
max_tokens = 4096

top_n_sigma = -1.0
top_k = 0
typical_p = 1.0
top_p = 1.0
min_p = 0.05

repeat_penalty = 1.0
repeat_last_n = 0
presence_penalty = 0.0
frequency_penalty = 0.0

xtc_probability = 0.0
dry_multiplier = 0.0
`,
		n, a.Note,
		n, a.Key,
		a.Key, n,
		a.Name, n,
		expansionImage,
		n,
		a.ModelID,
		a.Version,
		a.Wrapper,
		seeds,
	)
}
