package behaveq

import (
	"strings"
	"testing"
)

// wantMistralN24 is gen_expansion_defs.py's toml_for("mistral", 24) output,
// captured from the python oracle. It locks the TOML format byte-for-byte,
// including the literal \n sequences in the prompt_template and the trailing
// newline.
const wantMistralN24 = `# Behavioral-equivalence expansion (n=24) — Mistral-7B anchor.
# Generated by gen_expansion_defs.py. Materials, conditions, image, and sampler are
# identical across the three arms; only the model and its wrapper differ.
# Run: corpos-lab run-study studies/behavioral-equivalence-assay/study-defs/n24/mistral.toml \
#        -work studies/behavioral-equivalence-assay/runs/mistral-n24

name = "behavioral-equivalence-mistral-n24"
assay = "grounded-glyph-probe"
item_id = "behavioral-equivalence"

image = "localhost/lab-grounded-glyph-probe@sha256:d420b80f40889fec709f15067f5eccd8ad8219d3b616c7d53f2be45ec284f792"
network = "lab-net"

conditions = ["baseline", "duty_only", "corpus_only"]
runs_per_cell = 24

[model]
base_url = "http://llama-server:8081/v1"
model_id = "Mistral-7B-Instruct-v0.3.Q4_K_M.gguf"
version = "v0.3-q4km"
endpoint = "completion"
prompt_template = "[INST] {prompt}\n\n---\nNote: You are running as a single completion. There is no harness, no tools, no filesystem, no shell. You cannot call functions or read files. Give your answer directly as text. [/INST]"

[materials]
scenario = "../../materials/scenario.md"
duty     = "../../materials/duty.md"
corpus   = "../../materials/corpus.md"

[sampling]
temperature = 0.8
seeds = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24]
max_tokens = 4096

top_n_sigma = -1.0
top_k = 0
typical_p = 1.0
top_p = 1.0
min_p = 0.05

repeat_penalty = 1.0
repeat_last_n = 0
presence_penalty = 0.0
frequency_penalty = 0.0

xtc_probability = 0.0
dry_multiplier = 0.0
`

func TestTOMLForMistralN24ByteIdentical(t *testing.T) {
	arm, ok := ExpansionArmByKey("mistral")
	if !ok {
		t.Fatal("mistral arm not found")
	}
	got := TOMLFor(arm, 24)
	if got != wantMistralN24 {
		t.Errorf("TOMLFor(mistral, 24) mismatch:\n--- got ---\n%s\n--- want ---\n%s", got, wantMistralN24)
	}
}

func TestTOMLForAllArmsStructure(t *testing.T) {
	// Every arm renders with its own name, model id, wrapper, and the shared image;
	// the seed list scales with n.
	for _, arm := range ExpansionArms {
		got := TOMLFor(arm, 3)
		for _, want := range []string{
			"name = \"" + arm.Name + "-n3\"",
			"model_id = \"" + arm.ModelID + "\"",
			"version = \"" + arm.Version + "\"",
			"prompt_template = \"" + arm.Wrapper + "\"",
			"runs_per_cell = 3",
			"seeds = [1, 2, 3]",
			expansionImage,
		} {
			if !strings.Contains(got, want) {
				t.Errorf("arm %s: rendered TOML missing %q", arm.Key, want)
			}
		}
		if !strings.HasSuffix(got, "dry_multiplier = 0.0\n") {
			t.Errorf("arm %s: expected trailing dry_multiplier line + newline", arm.Key)
		}
	}
}

func TestExpansionArmByKey(t *testing.T) {
	for _, key := range []string{"mistral", "qwen38", "qwen2532"} {
		if a, ok := ExpansionArmByKey(key); !ok || a.Key != key {
			t.Errorf("ExpansionArmByKey(%q) = %v, %v", key, a.Key, ok)
		}
	}
	if _, ok := ExpansionArmByKey("nope"); ok {
		t.Error("ExpansionArmByKey(nope) should be false")
	}
}

func TestSeedList(t *testing.T) {
	cases := map[int]string{
		1: "1",
		3: "1, 2, 3",
		5: "1, 2, 3, 4, 5",
	}
	for n, want := range cases {
		if got := seedList(n); got != want {
			t.Errorf("seedList(%d) = %q, want %q", n, got, want)
		}
	}
	if got := seedList(0); got != "" {
		t.Errorf("seedList(0) = %q, want empty", got)
	}
}

// ExpansionArmByKey returns the arm with the given key, or false when none match.
func ExpansionArmByKey(key string) (ExpansionArm, bool) {
	for _, a := range ExpansionArms {
		if a.Key == key {
			return a, true
		}
	}
	return ExpansionArm{}, false
}
