// Package wrongpath ports the wrong-path-field-source study's provenance python
// to Go (chain eradicate-python-rewrite-in-go). The study backs the "Correct
// Verdicts, Wrong Field" paper (10.5281/zenodo.22716131).
//
// Three tools live here, all sans-IO: the caller reads the committed materials
// and run outputs and passes the data in; cmd/corpos-lab/pubscore_wrongpath.go
// does that wiring.
//
//   - GenStudyDefs  ports gen_study_defs.py — the 72-file study-def fan-out.
//   - Ablate        ports materials/make_ablated.py — the Marker/Aim ablation.
//   - Report        ports score.py — the deterministic scoring report.
package wrongpath

import (
	"fmt"
	"strings"
)

// The generation constants, copied verbatim from gen_study_defs.py.
const (
	genImage   = "localhost/lab-grounded-glyph-probe@sha256:cdada9161d969eba17e9a253f874c3a9ef35e16e4bf25c455263f8066f436bca"
	genNetwork = "lab-net"
	genBaseURL = "http://llama-server:8081/v1"
)

// Glyphs, Scenarios and Arms are the study matrix axes, in generation order.
var (
	Glyphs    = []string{"cas", "cgu", "fsb", "gop", "psc", "scb"}
	Scenarios = []string{"a", "b"}
	Arms      = []string{"base", "ablated"}
)

// subject is one per-model config from gen_study_defs.py SUBJECTS.
type subject struct {
	name      string
	modelID   string
	version   string
	open      string
	close     string
	maxTokens int
}

// Subjects is the ordered SUBJECTS table (python dict insertion order:
// mistral, qwen2532, qwen38).
var Subjects = []subject{
	{
		name: "mistral", modelID: "Mistral-7B-Instruct-v0.3.Q4_K_M.gguf",
		version: "v0.3-q4km", open: "[INST] ", close: " [/INST]", maxTokens: 1024,
	},
	{
		name: "qwen2532", modelID: "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
		version: "q4km", open: "<|im_start|>user\n", close: "<|im_end|>\n<|im_start|>assistant\n", maxTokens: 1024,
	},
	{
		name: "qwen38", modelID: "Qwen3.8-27B-Q4_K_M.gguf",
		version: "q4km", open: "<|im_start|>user\n", close: "<|im_end|>\n<|im_start|>assistant\n", maxTokens: 4096,
	},
}

// TOMLBasic renders s as a TOML basic string literal (escaped, quoted). Ported
// from gen_study_defs.toml_basic: backslash, double-quote, newline and tab are
// escaped in that order, then the whole is quoted.
func TOMLBasic(s string) string {
	s = strings.ReplaceAll(s, `\`, `\\`)
	s = strings.ReplaceAll(s, `"`, `\"`)
	s = strings.ReplaceAll(s, "\n", `\n`)
	s = strings.ReplaceAll(s, "\t", `\t`)
	return `"` + s + `"`
}

// SamplingBlock ports gen_study_defs.sampling_block. The em-dash is U+2014.
func SamplingBlock(maxTokens int) string {
	return "[sampling]\n" +
		"temperature = 0.8\n" +
		"seeds = [1, 2, 3, 4, 5, 6, 7, 8]\n" +
		fmt.Sprintf("max_tokens = %d\n\n", maxTokens) +
		"# Truncation: min_p only.\n" +
		"top_n_sigma = -1.0\n" +
		"top_k = 0\n" +
		"typical_p = 1.0\n" +
		"top_p = 1.0\n" +
		"min_p = 0.05\n\n" +
		"# Penalties: off — they would attenuate the axis-by-axis structure being measured.\n" +
		"repeat_penalty = 1.0\n" +
		"repeat_last_n = 0\n" +
		"presence_penalty = 0.0\n" +
		"frequency_penalty = 0.0\n\n" +
		"xtc_probability = 0.0\n" +
		"dry_multiplier = 0.0\n"
}

// subjectByName returns the subject config for a model name.
func subjectByName(name string) (subject, bool) {
	for _, s := range Subjects {
		if s.name == name {
			return s, true
		}
	}
	return subject{}, false
}

// Render ports gen_study_defs.render: the full TOML body for one cell. The
// instruction is the materials/base/INSTRUCTION.md text with trailing newlines
// stripped (python .read_text().rstrip("\n")).
func Render(arm, model, glyph, ab, instruction string) (string, error) {
	subj, ok := subjectByName(model)
	if !ok {
		return "", fmt.Errorf("unknown model %q", model)
	}
	template := subj.open + "{prompt}\n\n---\n" + instruction + subj.close
	terrainDir := "base"
	if arm != "base" {
		terrainDir = "ablated"
	}
	name := fmt.Sprintf("wrongpath-%s-%s-%s-%s", arm, model, glyph, ab)
	itemID := fmt.Sprintf("%s-%s", glyph, ab)
	return fmt.Sprintf(
		"# wrong-path-field-source — %s arm, %s, glyph %s, scenario %s\n"+
			"# Generated by gen_study_defs.py. Do not hand-edit; change the generator.\n"+
			"# Run: corpos-lab run-study studies/wrong-path-field-source/study-defs/%s/%s/%s-%s.toml \\\n"+
			"#        -work studies/wrong-path-field-source/runs/%s/%s/%s-%s\n"+
			"# Material paths resolve relative to THIS file.\n\n"+
			"name = \"%s\"\n"+
			"assay = \"grounded-glyph-probe\"\n"+
			"item_id = \"%s\"\n\n"+
			"image = \"%s\"\n"+
			"network = \"%s\"\n\n"+
			"conditions = [\"grounded_glyph\"]\n"+
			"runs_per_cell = 8\n\n"+
			"[model]\n"+
			"base_url = \"%s\"\n"+
			"model_id = \"%s\"\n"+
			"version = \"%s\"\n"+
			"endpoint = \"completion\"\n"+
			"prompt_template = %s\n\n"+
			"[materials]\n"+
			"glyph    = \"../../../materials/base/GLYPH_DEFINITION.md\"\n"+
			"ground   = \"../../../materials/%s/GLYPH_%s-terrain.md\"\n"+
			"scenario = \"../../../materials/base/SCENARIO_%s-%s.md\"\n\n"+
			"%s",
		arm, model, glyph, ab,
		arm, model, glyph, ab,
		arm, model, glyph, ab,
		name,
		itemID,
		genImage,
		genNetwork,
		genBaseURL,
		subj.modelID,
		subj.version,
		TOMLBasic(template),
		terrainDir, glyph,
		glyph, ab,
		SamplingBlock(subj.maxTokens),
	), nil
}

// StudyDef is one generated study definition: its path relative to the
// study-defs output root, and its TOML body.
type StudyDef struct {
	Arm     string
	Model   string
	Glyph   string
	AB      string
	RelPath string // "<arm>/<model>/<glyph>-<ab>.toml"
	Content string
}

// GenStudyDefs ports gen_study_defs.main's matrix: it produces every cell's
// study definition in generation order (arm, model, glyph, scenario). The
// instruction is the materials/base/INSTRUCTION.md text, already rstripped of
// trailing newlines by the caller.
func GenStudyDefs(instruction string) ([]StudyDef, error) {
	out := make([]StudyDef, 0, len(Arms)*len(Subjects)*len(Glyphs)*len(Scenarios))
	for _, arm := range Arms {
		for _, subj := range Subjects {
			for _, glyph := range Glyphs {
				for _, ab := range Scenarios {
					body, err := Render(arm, subj.name, glyph, ab, instruction)
					if err != nil {
						return nil, err
					}
					out = append(out, StudyDef{
						Arm: arm, Model: subj.name, Glyph: glyph, AB: ab,
						RelPath: fmt.Sprintf("%s/%s/%s-%s.toml", arm, subj.name, glyph, ab),
						Content: body,
					})
				}
			}
		}
	}
	return out, nil
}
