package cartographer

// Golden outputs captured from the python oracles (analyze.py, analyze_duty.py)
// run on the in-package test fixture. Regenerating: see cartographer_test.go
// fixture builders; the python was run on the equivalent JSON study dir.

const wantAnalyzeFixture = "== coverage rate per condition per class (k/n, Wilson 95%) ==\ncondition                              first-principles     non-first-principles\nbaseline                                2/6 [0.10,0.70]          1/6 [0.03,0.56]\nannotated_instrument                    6/6 [0.61,1.00]          5/6 [0.44,0.97]\ncartographer_instrument                 4/6 [0.30,0.90]          1/6 [0.03,0.56]\ncartographer_scan_instrument            4/6 [0.30,0.90]          4/6 [0.30,0.90]\n\n== primary interaction: annotated - cartographer coverage gap ==\n  first-principles       annotated 1.00 - cartographer 0.67 = gap +0.33\n  non-first-principles   annotated 0.83 - cartographer 0.17 = gap +0.67\n  Fisher (annotated vs cartographer, non-first-principles pooled): p=0.0801\n\n== scan recovery: cartographer vs cartographer+scan, per non-FP taboo ==\n  nf-gamma                                   (meta_routing    , scan-target) cart 1/3 -> scan 3/3  p=0.4\n  nf-delta                                   (corpus_empirical, not-targeted) cart 0/3 -> scan 1/3  p=1\n\n== per-taboo coverage rate (k/n) by condition ==\ntaboo                                       class             baseline annotated cartograp cartograp\nfp-alpha                                    first_principles       1/3       3/3       2/3       2/3\nfp-beta                                     first_principles       1/3       3/3       2/3       2/3\nnf-gamma                                    meta_routing           0/3       2/3       1/3       3/3\nnf-delta                                    corpus_empirical       1/3       3/3       0/3       1/3\n"

const wantAnalyzeDutyFixture = "== per-duty mean coverage rate (n=30 duties/condition) ==\n  cartographer_instrument          FP 0.667  nonFP 0.167\n  cartographer_scan_instrument     FP 0.667  nonFP 0.667\n  annotated_instrument             FP 1.000  nonFP 0.833\n  baseline                         FP 0.333  nonFP 0.167\n\n== registered interaction (duty-level, permutation) ==\n  per-duty (FP-nonFP): annotated mean +0.167, cartographer mean +0.500\n  permutation p (annotated vs cartographer) = 0.7\n\n== non-first-principles, duty-level (covers >=1 non-FP hazard) ==\n  annotated 3/30, cartographer 1/30, Fisher p=0.61\n\n== first-principles, duty-level (cartographer vs baseline) ==\n  cartographer mean 0.667, baseline mean 0.333, permutation p=0.6\n\n== cartographer first-principles per-taboo spread ==\n  alpha 2/30, beta 2/30\n  range 2/30 to 2/30\n\n== rater-free keyword presence (responses mentioning the hazard) ==\n  baseline                         routing 1/30  durability(advisory) 0/30  constraint(discovered) 1/30\n  annotated_instrument             routing 1/30  durability(advisory) 1/30  constraint(discovered) 1/30\n  cartographer_instrument          routing 1/30  durability(advisory) 0/30  constraint(discovered) 0/30\n  cartographer_scan_instrument     routing 1/30  durability(advisory) 1/30  constraint(discovered) 0/30\n"
