#!/usr/bin/env python3
"""Generate the wrong-path-field-source study definitions.

The corpos-lab runner takes one model, one glyph, one terrain, one scenario per
study.toml, so this study's matrix is a fan-out: 2 arms x 3 subjects x 6 glyphs
x 2 scenarios = 72 files. They are generated, not hand-written, so the whole
matrix stays consistent and a change to the sampler or wrapper touches one place.

Run from the study directory:  python3 gen_study_defs.py
Output:  study-defs/<arm>/<model>/<glyph>-<ab>.toml

Each file uses the grounded_glyph condition, which assembles
glyph-definition "---" terrain "---" scenario. The four-field instruction rides
in the model's prompt_template, after the assembled material. The two arms
differ only in which terrain the `ground` slot points at (base vs ablated).
"""
from __future__ import annotations

import pathlib

HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "study-defs"

# The CURRENT probe image (post the 2026-09-09 truncation fix). New arms use
# this, never the older 8218... digest — see the matched-content study notes.
IMAGE = "localhost/lab-grounded-glyph-probe@sha256:e159c2b88ce748e0c1fa7e592fa39f3c599d38d2cb2916b14e3a7f9f658dacb1"
NETWORK = "corpos-net"
BASE_URL = "http://llama-server:8081/v1"

GLYPHS = ["cas", "cgu", "fsb", "gop", "psc", "scb"]
SCENARIOS = ["a", "b"]
ARMS = ["base", "ablated"]

# The four-field instruction is the single source of truth in
# materials/base/INSTRUCTION.md, so the file on disk is exactly what the wrapper
# delivers. It is adapted from v10: the one clause "the glyph above and the trace
# below" is corrected to "above" because the assembly places both the glyph and
# the trace before the instruction; the response format is verbatim.
INSTRUCTION = (HERE / "materials" / "base" / "INSTRUCTION.md").read_text().rstrip("\n")

# Per-subject config. thinking=True omits the empty <think></think> block so the
# model reasons; it also gets a larger token budget so a long trace does not
# truncate to an empty answer.
SUBJECTS = {
    "mistral": {
        "model_id": "Mistral-7B-Instruct-v0.3.Q4_K_M.gguf",
        "version": "v0.3-q4km",
        "open": "[INST] ",
        "close": " [/INST]",
        "max_tokens": 1024,
    },
    "qwen2532": {
        "model_id": "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        "version": "q4km",
        "open": "<|im_start|>user\n",
        "close": "<|im_end|>\n<|im_start|>assistant\n",
        "max_tokens": 1024,
    },
    "qwen38": {
        "model_id": "Qwen3.8-27B-Q4_K_M.gguf",
        "version": "q4km",
        # Thinking ON: no empty think block. Larger budget for the reasoning.
        "open": "<|im_start|>user\n",
        "close": "<|im_end|>\n<|im_start|>assistant\n",
        "max_tokens": 4096,
    },
}


def toml_basic(s: str) -> str:
    """Render s as a TOML basic string literal (escaped, quoted)."""
    s = s.replace("\\", "\\\\").replace('"', '\\"').replace("\n", "\\n").replace("\t", "\\t")
    return '"' + s + '"'


def sampling_block(max_tokens: int) -> str:
    return (
        "[sampling]\n"
        "temperature = 0.8\n"
        "seeds = [1, 2, 3, 4, 5, 6, 7, 8]\n"
        f"max_tokens = {max_tokens}\n\n"
        "# Truncation: min_p only.\n"
        "top_n_sigma = -1.0\n"
        "top_k = 0\n"
        "typical_p = 1.0\n"
        "top_p = 1.0\n"
        "min_p = 0.05\n\n"
        "# Penalties: off \u2014 they would attenuate the axis-by-axis structure being measured.\n"
        "repeat_penalty = 1.0\n"
        "repeat_last_n = 0\n"
        "presence_penalty = 0.0\n"
        "frequency_penalty = 0.0\n\n"
        "xtc_probability = 0.0\n"
        "dry_multiplier = 0.0\n"
    )


def render(arm: str, model: str, glyph: str, ab: str) -> str:
    subj = SUBJECTS[model]
    template = f"{subj['open']}{{prompt}}\n\n---\n{INSTRUCTION}{subj['close']}"
    terrain_dir = "base" if arm == "base" else "ablated"
    name = f"wrongpath-{arm}-{model}-{glyph}-{ab}"
    item_id = f"{glyph}-{ab}"
    return (
        f"# wrong-path-field-source \u2014 {arm} arm, {model}, glyph {glyph}, scenario {ab}\n"
        f"# Generated by gen_study_defs.py. Do not hand-edit; change the generator.\n"
        f"# Run: corpos-lab run-study studies/wrong-path-field-source/study-defs/{arm}/{model}/{glyph}-{ab}.toml \\\n"
        f"#        -work studies/wrong-path-field-source/runs/{arm}/{model}/{glyph}-{ab}\n"
        f"# Material paths resolve relative to THIS file.\n\n"
        f'name = "{name}"\n'
        f'assay = "grounded-glyph-probe"\n'
        f'item_id = "{item_id}"\n\n'
        f'image = "{IMAGE}"\n'
        f'network = "{NETWORK}"\n\n'
        f'conditions = ["grounded_glyph"]\n'
        f"runs_per_cell = 8\n\n"
        f"[model]\n"
        f'base_url = "{BASE_URL}"\n'
        f'model_id = "{subj["model_id"]}"\n'
        f'version = "{subj["version"]}"\n'
        f'endpoint = "completion"\n'
        f"prompt_template = {toml_basic(template)}\n\n"
        f"[materials]\n"
        f'glyph    = "../../../materials/base/GLYPH_DEFINITION.md"\n'
        f'ground   = "../../../materials/{terrain_dir}/GLYPH_{glyph}-terrain.md"\n'
        f'scenario = "../../../materials/base/SCENARIO_{glyph}-{ab}.md"\n\n'
        f"{sampling_block(subj['max_tokens'])}"
    )


def main() -> None:
    count = 0
    for arm in ARMS:
        for model in SUBJECTS:
            d = OUT / arm / model
            d.mkdir(parents=True, exist_ok=True)
            for glyph in GLYPHS:
                for ab in SCENARIOS:
                    (d / f"{glyph}-{ab}.toml").write_text(render(arm, model, glyph, ab))
                    count += 1
    print(f"wrote {count} study definitions under {OUT.relative_to(HERE)}/")


if __name__ == "__main__":
    main()
