#!/usr/bin/env python3
"""Generate the behavioral-equivalence expansion study definitions for a given n.

Writes study-defs/n<N>/{mistral,qwen38,qwen2532}.toml. The three arms share the
conditions, the materials, the pinned image, and the complete sampler chain; they
differ only in the model and its instruct wrapper. Seeds are 1..N, one per
replicate (the validator requires exactly one unique seed per run).

Usage: python3 gen_expansion_defs.py <N>
"""
import os
import sys

IMAGE = "localhost/lab-grounded-glyph-probe@sha256:d420b80f40889fec709f15067f5eccd8ad8219d3b616c7d53f2be45ec284f792"

NOTE = ("Note: You are running as a single completion. There is no harness, no tools, "
        "no filesystem, no shell. You cannot call functions or read files. Give your "
        "answer directly as text.")

ARMS = {
    "mistral": {
        "name": "behavioral-equivalence-mistral",
        "model_id": "Mistral-7B-Instruct-v0.3.Q4_K_M.gguf",
        "version": "v0.3-q4km",
        "wrapper": f"[INST] {{prompt}}\\n\\n---\\n{NOTE} [/INST]",
        "note": "Mistral-7B anchor.",
    },
    "qwen38": {
        "name": "behavioral-equivalence-qwen38",
        "model_id": "Qwen3.8-27B-Q4_K_M.gguf",
        "version": "q4km",
        "wrapper": f"<|im_start|>user\\n{{prompt}}\\n\\n---\\n{NOTE}<|im_end|>\\n<|im_start|>assistant\\n<think>\\n\\n</think>\\n\\n",
        "note": "Qwen3.8-27B, thinking pinned OFF via the closed empty <think> block.",
    },
    "qwen2532": {
        "name": "behavioral-equivalence-qwen2532",
        "model_id": "Qwen2.5-32B-Instruct-Q4_K_M.gguf",
        "version": "q4km",
        "wrapper": f"<|im_start|>user\\n{{prompt}}\\n\\n---\\n{NOTE}<|im_end|>\\n<|im_start|>assistant\\n",
        "note": ("Qwen2.5-32B, non-thinking. MUST be served at ctx 8192, not 32768 "
                 "(the 32B + a 32768 KV cache overruns the 24 GB GPU; wrong-path-field-source). "
                 "Prompt ~1900 + max_tokens 4096 fits 8192."),
    },
}


def toml_for(arm_key, n):
    a = ARMS[arm_key]
    seeds = ", ".join(str(i) for i in range(1, n + 1))
    return f"""# Behavioral-equivalence expansion (n={n}) — {a['note']}
# Generated by gen_expansion_defs.py. Materials, conditions, image, and sampler are
# identical across the three arms; only the model and its wrapper differ.
# Run: corpos-lab run-study studies/behavioral-equivalence-assay/study-defs/n{n}/{arm_key}.toml \\
#        -work studies/behavioral-equivalence-assay/runs/{arm_key}-n{n}

name = "{a['name']}-n{n}"
assay = "grounded-glyph-probe"
item_id = "behavioral-equivalence"

image = "{IMAGE}"
network = "corpos-net"

conditions = ["baseline", "duty_only", "corpus_only"]
runs_per_cell = {n}

[model]
base_url = "http://llama-server:8081/v1"
model_id = "{a['model_id']}"
version = "{a['version']}"
endpoint = "completion"
prompt_template = "{a['wrapper']}"

[materials]
scenario = "../../materials/scenario.md"
duty     = "../../materials/duty.md"
corpus   = "../../materials/corpus.md"

[sampling]
temperature = 0.8
seeds = [{seeds}]
max_tokens = 4096

top_n_sigma = -1.0
top_k = 0
typical_p = 1.0
top_p = 1.0
min_p = 0.05

repeat_penalty = 1.0
repeat_last_n = 0
presence_penalty = 0.0
frequency_penalty = 0.0

xtc_probability = 0.0
dry_multiplier = 0.0
"""


def main():
    if len(sys.argv) != 2:
        print(__doc__)
        sys.exit(2)
    n = int(sys.argv[1])
    base = os.path.dirname(os.path.abspath(__file__))
    outdir = os.path.join(base, "study-defs", f"n{n}")
    os.makedirs(outdir, exist_ok=True)
    for arm in ARMS:
        path = os.path.join(outdir, f"{arm}.toml")
        with open(path, "w") as f:
            f.write(toml_for(arm, n))
        print(f"wrote {path}")


if __name__ == "__main__":
    main()
